services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambda-lint_pydocstyle
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAJTUSZCFJO2PNDFHQ
      secret_access_key:
        secure: gn4xmZ4mYZEKtW+4uGU5WRkW6QW5rJQ16PvTVXzCaiXp9i0jIakKyPdh7gC2BoLoxJI5+BZz0KhtyvDXVBtc2rzR47eo/mrGxDKNiMIMchFjwKuCeQvUrEcKeeeydXLRSHRtzNYMdzWScMycifhS8trkpcEsm9o8ybSts1bsA8mGBYy+ag5ZoxR28hPXH2h+vfe50gTaiXqpuCJI63z3c36DSkACtAIrpL99nC4Km7lZSO5Sa2T00fhlyZQrYPup4xdvc2UkN2vzMC1b1FgTlAdAbgH8I2ZDQNhYHqURvDhhx02oIfQ4DuTg2e7fRh27tk2hBfhOOoTx+raqtg9569SnRhS9Hly710g6uyxDAo6Z67JksfZ+Hp3MB8crc/tvEY5ViCzyhjTGxynFPXsqq9qUjp2NAnL9N9ZuGn8rznTlYVOSzTj53ZC4AG9OCg2ifPCGBMfw2fWjN3SiXtKlNdljcZ8KfSq3zn2anPnYwOQHQ0TvJ63vHkGVE/aMeu6le4zt2Es4/A46KzmmJykQ8/alLmg7Z6O6icOX1woxdfL7uBJKglGB7DaRQZJjRmtb5/4FODGi+/ICV/kldtiZrzDWeGdZZkkse6LZPIbZKwnznsgXcr9r54kI1FuZfRu1+lC5tvCGFO5DZrlOEZY8GI3gumiqMqcIlbn3e+1mXxg=
      on:
        repo: FussyFox/pydocstyle
